# Generated by Django 4.2.6 on 2025-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
