# Generated by Django 4.2.6 on 2025-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_image.webp', null=True, upload_to=''),
        ),
    ]
